#!/usr/bin/env zsh

#{{ envpathmerge <name> <path>
#
#   ディレクトリ <path> と <path>/bin が存在する場合に
#   環境変数 <name>=<path> を設定し PATH に $path/bin を追加する
#   ディレクトリが存在しない場合には、変数 <name> を削除する
#}}

emulate -L zsh

autoload -Uz pathmunge

if [[ -d "$2" && -d "$2/bin" ]]; then
    typeset -gx $1
    eval $1="$2"
    pathmunge "$2/bin"
else
    eval unset $1
fi

# eof
